Add title page
hsfl-pltp/pltp-thesis pull request #1
Opened 2022-02-27 08:57 UTC by hingew

Adding the title page. This is required by the HS-Flensburg. 
The original title page: https://hs-flensburg.de/sites/default/files/formular/DeckblattBA_0.pdf

2022-02-27 08:58 UTC, hingew commented
[thesis.pdf](https://github.com/hsfl-pltp/pltp-thesis/files/8148370/thesis.pdf)

2022-02-28 07:41 UTC, jan-christiansen requested changes

2022-02-28 07:41 UTC, jan-christiansen commented on LaTeX/thesis.tex
> +    \large Matrikel-N\textsuperscript{\underline{o}}: & \hrule
Warum Matrikel-No?

2022-03-10 19:16 UTC, hingew commented on LaTeX/thesis.tex
> +    \large Matrikel-N\textsuperscript{\underline{o}}: & \hrule
Es sollte Matrikel-Nr sein. Werde ich anpassen.

2022-03-10 19:19 UTC, hingew commented on LaTeX/thesis.tex
> +    \large Matrikel-N\textsuperscript{\underline{o}}: & \hrule
Habe ich angepasst.

2022-03-11 04:51 UTC, merged